### ISSUE TITLE
Rename maxnumemailaccount

### ISSUE THREAD

**Issue by peterhellberg** [GleSYS/API#12]
The service limit `maxnumemailaccount` in *account/info* should probably be renamed `maxnumemailaccounts`

**Comment by wecc** [comment]
Thanks for reporting! Sorry it took so long for us to respond :cry: 

We've added `maxnumemailaccounts` in addition to `maxnumemailaccount` (now deprecated) and will remove `maxnumemailaccount` at a later date.
