### ISSUE TITLE
expression expected in cpumonitor

### ISSUE THREAD

**Issue by to8gal** [GleSYS/API#21]
I got the [: : integer expression expected on line 5 and 14 after adding quotes

and the [: -ge: unary operator expected on line 5 and [: -lt: unary operator expected on line 14 if quotes are not added.

**Comment by wecc** [comment]
Thanks for reporting @to8gal!

Seems that the script assumed `.` as a decimal separator but this can vary depending on the system locale. I've submitted a patch that should solve this issue, see #22.

**Comment by to8gal** [comment]
Great thanks, I will try it straight away.
Luca Cagnassi
Media Designer at 5preview AB

(+46) 722111977

Luca Cagnassi is also: www.to8gal.com <http://www.to8gal.com/>

“Think Green – Please do not print this email or any printable file attached unless you really need to“

**Comment by to8gal** [comment]
unfortunately still same error, exactly the same.

**Comment by wecc** [comment]
What distribution and version are you using? We tested it on Debian and Ubuntu and it worked fine.

**Comment by to8gal** [comment]
Ubuntu 12.04
Luca Cagnassi
Media Designer at 5preview AB

(+46) 722111977

Luca Cagnassi is also: www.to8gal.com <http://www.to8gal.com/>

“Think Green – Please do not print this email or any printable file attached unless you really need to“

**Comment by wecc** [comment]
Just merged #23, can you give it another go?

**Comment by to8gal** [comment]
work now, Thanks

**Comment by wecc** [comment]
:+1:
