### ISSUE TITLE
Parameter for domain/renew

### ISSUE THREAD

**Issue by emilv** [glesys/API#24]
It would be nice with a `months` parameter for the domain/renew command. Some TLDs support this by allowing the renewal period to be 12-120 months, but this is not visible in the Glesys API.

**Comment by wecc** [comment]
Is my understanding correct that the reason for this is to be able to renew a domain for let's say 20 months instead of even 12 month intervals?

**Comment by emilv** [comment]
Yes! That way we can synchronize our domain names to reduce the number of
invoices. I think this parameter might also be allowed on domain creation
in the EPP protocol.


//Emil

2016-12-28 9:32 GMT+01:00 Christoffer Persson <notifications@github.com>:

**Comment by emil-nasso** [comment]
Renewing per month is currently not possible with the domain provider we are currently using. I like the idea though and will forward your request.

**Comment by wecc** [comment]
If our domain provider makes this a reality we'll look into support renewing domains with a custom number of months.
