### ISSUE TITLE
networkadapter/create optional value adaptertype not validated.

### ISSUE THREAD

**Issue by norrland** [glesys/API#26]
When creating adapters via the api the 'adaptertype' argument is not checked, and is accepted as it is.

It would be helpful to get a warning in such case.

This is valid at this moment.
```
$ curl -X POST -d '{'serverid':'vz123456', 'adaptertype':'korven'}' -k --basic -u [API-USER]:[API-KEY] https://api.glesys.com/networkadapter/create/
```

**Comment by wecc** [comment]
Thanks for the report @norrland. I've added this issue to our internal bug tracker and will report back when it has been fixed.

**Comment by brother** [comment]
We've tightened the validation and incorrect adapter types will fail. Earlier incorrect adapter types would fallback to default value.
