### ISSUE TITLE
Documentation for server/destroy unclear

### ISSUE THREAD

**Issue by MrDaar** [glesys/API#28]
In the documentation it does not stipulate what type "keepip" parameter should be, and possibly in other places where there are booleans.
i.e. Would it be, `"yes/no", "y/n", "1/0", 1/0, true/false`?
Would `"keepip": "NULL"` keep or not keep the IP?

**Comment by wecc** [comment]
Thank you for raising this issue @MrDaar!

I've submitted a PR internally updating the docs explaining the `keepip` flag a bit more (including example values). It should be live shortly.

To answer your question the `keepip` flag is required and accepts the values `1`, `0`, `true`, `false`, `yes` and `no`. Any other values would be rejected. `null` would not be allowed and you'd get an error.

This behavior is shared by all (required) "boolean" flags in our API. We should clarify this in the documentation and make sure the defaults are explained as well for any optional flags.

**Comment by MrDaar** [comment]
Brilliant! Thanks! :)
