### ISSUE TITLE
loadbalancer/create ip: 'none' fails

### ISSUE THREAD

**Issue by norrland** [glesys/API#30]
When creating a loadbalancer it is not possible to create it without any ip address even if the documentation says so.

```
curl -X POST -d '{'name':'my-lb', 'datacenter':'Falkenberg', 'ip':'none'}' -k --basic -u [API-USER]:[API-KEY] https://api.glesys.com/loadbalancer/create/

'status': {'code': 400,
   'text': 'ip or ipv6 required',
   'timestamp': '2017-08-29T10:33:59+02:00',
   'transactionid': None}
```

**Comment by wecc** [comment]
I suspect the documentation is a bit out of date in this case, sorry about that.

Creating a Load Balancer requires both the `ip` and `ipv6` parameters to be present and both cannot be set to `none` – any other combination should be valid.

I'll make sure we update the docs. Thanks for reporting!

**Comment by wecc** [comment]
Docs has been updated, closing this.

> At least one of `ip` and `ipv6` has to be present with a value other than `none` (default). Valid values are IPv4/IPv6 addresses or `any` (to randomly assign a new IP).

– https://github.com/GleSYS/API/wiki/API-Documentation#loadbalancercreate
