### ISSUE TITLE
servers/create lists users as an optional parameter

### ISSUE THREAD

**Issue by Yopi** [glesys/API#35]
The documentation lists the users parameter as optional, but the API responds that it is.

`curl -X POST --basic -u X:Y --data-urlencode "datacenter=Falkenberg" --data-urlencode "platform=KVM" --data-urlencode "hostname=abc" --data-urlencode "templatename=ubuntu-18-04" --data-urlencode "disksize=5" --data-urlencode "memorysize=512" --data-urlencode "cpucores=1" https://api.glesys.com/server/create/`

```
 <status>
  <code>400</code>
  <timestamp>2020-02-08T23:53:35+01:00</timestamp>
  <text>The users field is required.</text>
  <transactionid/>
 </status>
```

Presumably due to KVM being newly added/in beta based on the description here: https://github.com/glesys/glesys-go/pull/21

**Comment by wecc** [comment]
Hi @Yopi!

Yes, the `users`-parameter is optional _unless_ `platform=kvm`. Unfortunately there's currently no better way for us to mark it "optional only when..." in our automatically generated documentation.

However, we should add a note about this in the endpoint description.

Thank you for bringing this to our attention!

**Comment by wecc** [comment]
The documentation over at https://github.com/glesys/API/wiki/API-Documentation#servercreate has now been extended with details about the `users` argument.

Thanks again for the report!
